# Generated by Django 2.2.17 on 2021-01-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='LivreSuggere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('auteur', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='biblio.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('auteur', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='biblio.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('livres', models.ManyToManyField(to='biblio.Livre')),
            ],
        ),
    ]
