# Generated by Django 2.2.17 on 2021-01-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livresuggere',
            name='validation',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
