# Generated by Django 2.2.17 on 2021-01-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_livresuggere_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livresuggere',
            name='validation',
        ),
    ]
