# Generated by Django 2.2.17 on 2021-01-28 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblio', '0004_liste_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liste',
            old_name='id_user',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('avatar', models.ImageField(upload_to='')),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('pays', models.CharField(blank=True, max_length=30)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
