# Generated by Django 2.2.17 on 2021-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0005_auto_20210128_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liste',
            old_name='titre',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
