# Generated by Django 2.2.17 on 2021-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_auto_20210205_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
