# Generated by Django 2.2.17 on 2021-02-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0007_auto_20210205_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
