# Generated by Django 2.2.17 on 2021-02-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0010_auto_20210205_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
