# Generated by Django 2.2.17 on 2021-02-05 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblio', '0011_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('dateNaissance', models.DateField(blank=True, default='', null=True)),
                ('bio', models.TextField(blank=True, default='Coucou', max_length=500)),
                ('pays', models.CharField(blank=True, default='France', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
