# Generated by Django 2.2.17 on 2021-02-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0016_auto_20210206_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profil',
            name='pays',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
