# Generated by Django 2.2.17 on 2021-02-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0017_auto_20210206_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='dateNaissance',
        ),
    ]
