# Generated by Django 2.2.17 on 2021-02-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0018_remove_profil_datenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
